// constants/index.jsx

export const products = [
    {
      id: 1,
      name: "Wireless Bluetooth Headphones",
      description:
        "High-quality wireless Bluetooth headphones with noise-canceling feature, deep bass, and up to 20 hours of battery life. Perfect for travel, work, and daily use.",
      price: 59.99,
      image: "/Images/products/1.jpeg",
      category: "Electronics",
      rating: 4.5,
      stock: 25,
      brand: "SoundBeat",
      features: [
        "Bluetooth 5.0",
        "Noise Cancelling",
        "20-hour Battery Life",
        "Comfortable Fit",
      ],
    },
    {
      id: 2,
      name: "Smart Fitness Watch",
      description:
        "Track your fitness levels with a sleek and lightweight smartwatch. Features heart rate monitoring, sleep tracking, and over 15 workout modes.",
      price: 89.99,
      image: "/Images/products/2.jpeg",
      category: "Wearables",
      rating: 4.3,
      stock: 15,
      brand: "FitPro",
      features: [
        "Heart Rate Monitor",
        "Sleep Tracking",
        "Water Resistant",
        "Customizable Watch Faces",
      ],
    },
    {
      id: 3,
      name: "4K Action Camera",
      description:
        "Capture your adventures with this 4K action camera. Waterproof, durable, and perfect for outdoor sports, with high-definition video recording and image stabilization.",
      price: 120.0,
      image: "/Images/products/3.jpeg",
      category: "Cameras",
      rating: 4.7,
      stock: 10,
      brand: "GoExtreme",
      features: [
        "4K Video Recording",
        "Image Stabilization",
        "Waterproof up to 30m",
        "Wide-Angle Lens",
      ],
    },
    {
      id: 4,
      name: "Ergonomic Office Chair",
      description:
        "An ergonomic chair designed for ultimate comfort and posture support. Ideal for long hours of work or gaming, with adjustable height and lumbar support.",
      price: 150.0,
      image: "/Images/products/4.jpeg",
      category: "Furniture",
      rating: 4.6,
      stock: 5,
      brand: "ComfortSeat",
      features: [
        "Adjustable Height",
        "Lumbar Support",
        "Breathable Mesh Back",
        "High-Density Foam Cushion",
      ],
    },
    {
      id: 5,
      name: "Portable Coffee Maker",
      description:
        "Enjoy fresh coffee anywhere with this portable coffee maker. Simple to use, lightweight, and compatible with ground coffee and coffee pods.",
      price: 34.99,
      image: "/Images/products/1.jpeg",
      category: "Home Appliances",
      rating: 4.4,
      stock: 30,
      brand: "BrewAnywhere",
      features: [
        "Lightweight Design",
        "Easy to Clean",
        "Compatible with Pods and Ground Coffee",
        "Eco-Friendly",
      ],
    },
    {
      id: 6,
      name: "Wireless Charging Pad",
      description:
        "Quickly charge your phone wirelessly with this sleek and compact charging pad. Compatible with most Qi-enabled devices and perfect for home or office use.",
      price: 19.99,
      image: "/Images/products/3.jpeg",
      category: "Accessories",
      rating: 4.2,
      stock: 40,
      brand: "PowerUp",
      features: [
        "Fast Charging",
        "Overheating Protection",
        "Compact Design",
        "LED Indicator",
      ],
    },
    // Add more products as needed
  ];


// reviews section data

export const reviews = [
  {
    id: 1,
    name: "Aarav Mehta",
    rating: 5,
    description: "An absolutely fantastic experience! This product has exceeded my expectations in every way. The quality is remarkable, and the features are genuinely helpful. Highly recommend to anyone considering a purchase.",
    longDescription: "I was skeptical at first, but after using it for a few weeks, I can confidently say it’s worth every penny. The attention to detail, from packaging to performance, is top-notch. Customer service was also very responsive, and the delivery was on time. I’ve been using it daily, and it has significantly improved my productivity. It's one of those products that makes you wonder how you managed without it before.",
    date: "October 12, 2024",
    photo: "/Images/profilelogo/1.jpg",
  },
  {
    id: 2,
    name: "Neha Singh",
    rating: 4,
    description: "Great product overall. Minor improvements could make it perfect, but I’m pleased with my purchase and would definitely recommend it to friends.",
    longDescription: "The product works exactly as described. I found the setup easy, and it’s been running smoothly since day one. There was a minor issue with the installation, but it was easily resolved by the support team. The quality is solid, and the design is stylish, fitting perfectly with my decor. I hope they release some additional features in future updates, but even now, it’s very functional.",
    date: "September 30, 2024",
    photo: "/Images/profilelogo/2.jpg",
  },
  {
    id: 3,
    name: "Rohan Verma",
    rating: 5,
    description: "Exceptional value for money! I am extremely satisfied and will definitely be a returning customer for future products.",
    longDescription: "From the very first use, it was clear that this product is built with quality in mind. The features included at this price point are unbeatable, and I feel like I got more than my money’s worth. It has been reliable, and I appreciate the little details that show thoughtfulness in design. It’s not often that I write reviews, but this one deserves recognition.",
    date: "August 25, 2024",
    photo: "/Images/profilelogo/3.webp",
  },
  {
    id: 4,
    name: "Meera Kapoor",
    rating: 3,
    description: "Good product, but could use some improvements. It meets basic expectations, but a few areas need work for it to reach its full potential.",
    longDescription: "After using it for a few weeks, I can see where improvements can be made. The product functions as advertised, but I had hoped for a smoother experience. It’s solid in quality, but a couple of features are not as user-friendly as they could be. Customer support was helpful, but I would like to see future updates that address these small issues.",
    date: "July 15, 2024",
    photo: "/Images/profilelogo/4.jpg",
  },
  {
    id: 5,
    name: "Amit Joshi",
    rating: 4,
    description: "Solid performance and quality, but a bit pricey. I’m happy with the purchase overall and would recommend it to those who don’t mind spending a bit extra for quality.",
    longDescription: "The product has been excellent in terms of functionality and reliability. It’s clear that a lot of thought went into the design, and it’s been a valuable addition to my daily routine. The only downside for me is the price; it’s a bit higher than similar options. However, I understand that quality comes at a cost, and I’m ultimately satisfied with my choice.",
    date: "June 10, 2024",
    photo: "/Images/profilelogo/5.jpg",
  },
];

// this list is shown in products sreen and not in home page product, the home page produt list is above

// src/constants/index.jsx

export const productlist = [
  {
    id: 1,
    name: "Apple iPhone 13 Pro",
    price: 999,
    rating: 4.7,
    imageUrl: "https://example.com/iphone13pro.jpg",
    description: "The latest iPhone with advanced dual-camera system, A15 Bionic chip, and Super Retina XDR display.",
    category: "Electronics",
    brand: "Apple",
    specifications: {
      storage: "128GB",
      color: "Graphite",
      screen: "6.1 inches",
      battery: "3095 mAh",
      processor: "A15 Bionic",
    },
    reviews: [
      { user: "John", comment: "Amazing phone!", rating: 5 },
      { user: "Sara", comment: "Great camera quality.", rating: 4 },
    ],
  },
  {
    id: 2,
    name: "Samsung Galaxy S22 Ultra",
    price: 1199,
    rating: 4.6,
    imageUrl: "https://example.com/galaxyS22ultra.jpg",
    description: "Experience the next generation of mobile with the Galaxy S22 Ultra featuring S-Pen support.",
    category: "Electronics",
    brand: "Samsung",
    specifications: {
      storage: "256GB",
      color: "Phantom Black",
      screen: "6.8 inches",
      battery: "5000 mAh",
      processor: "Snapdragon 8 Gen 1",
    },
    reviews: [
      { user: "Mike", comment: "Fantastic performance.", rating: 5 },
      { user: "Anna", comment: "Love the screen size.", rating: 4 },
    ],
  },
  {
    id: 3,
    name: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
    price: 349,
    rating: 4.8,
    imageUrl: "https://example.com/sonywh1000xm4.jpg",
    description: "Industry-leading noise-canceling headphones with Alexa voice control.",
    category: "Electronics",
    brand: "Sony",
    specifications: {
      color: "Black",
      batteryLife: "30 hours",
      noiseCancelling: "Yes",
      microphone: "Built-in",
    },
    reviews: [
      { user: "Emma", comment: "Best noise canceling headphones.", rating: 5 },
      { user: "Dave", comment: "Very comfortable to wear.", rating: 4 },
    ],
  },
  {
    id: 4,
    name: "Dell XPS 13 Laptop",
    price: 1199,
    rating: 4.5,
    imageUrl: "https://example.com/dellxps13.jpg",
    description: "Ultra-thin and light laptop with InfinityEdge display and 11th Gen Intel Core i7 processor.",
    category: "Computers",
    brand: "Dell",
    specifications: {
      storage: "512GB SSD",
      color: "Silver",
      screen: "13.3 inches",
      processor: "Intel Core i7",
      ram: "16GB",
    },
    reviews: [
      { user: "Alice", comment: "Perfect for my work needs!", rating: 5 },
      { user: "Bob", comment: "Great design and performance.", rating: 4 },
    ],
  },
  {
    id: 5,
    name: "HP Spectre x360 Convertible Laptop",
    price: 1299,
    rating: 4.4,
    imageUrl: "https://example.com/hpspectrex360.jpg",
    description: "Versatile 2-in-1 laptop with a touch screen and 360-degree hinge.",
    category: "Computers",
    brand: "HP",
    specifications: {
      storage: "1TB SSD",
      color: "Nightfall Black",
      screen: "13.3 inches",
      processor: "Intel Core i7",
      ram: "16GB",
    },
    reviews: [
      { user: "Chris", comment: "Great for both work and media.", rating: 5 },
      { user: "Dana", comment: "I love the touchscreen.", rating: 4 },
    ],
  },
  // ... Continue adding products up to 30
  {
    id: 6,
    name: "Apple MacBook Pro 16-inch",
    price: 2399,
    rating: 4.8,
    imageUrl: "https://example.com/macbookpro16.jpg",
    description: "High-performance MacBook with M1 Pro chip, ideal for professionals.",
    category: "Computers",
    brand: "Apple",
    specifications: {
      storage: "512GB SSD",
      color: "Space Gray",
      screen: "16 inches",
      processor: "M1 Pro",
      ram: "16GB",
    },
    reviews: [
      { user: "Edward", comment: "Super fast and powerful.", rating: 5 },
      { user: "Fiona", comment: "Great for my video editing.", rating: 4 },
    ],
  },
  // Add additional products to reach a total of 30 in a similar format.

  {
    id: 7,
    name: "Asus ROG Zephyrus G14 Gaming Laptop",
    price: 1499,
    rating: 4.6,
    imageUrl: "https://example.com/rogzephyrusg14.jpg",
    description: "Compact and powerful gaming laptop with AMD Ryzen 9 and NVIDIA GeForce RTX 3060.",
    category: "Computers",
    brand: "Asus",
    specifications: {
      storage: "1TB SSD",
      color: "Eclipse Gray",
      screen: "14 inches",
      processor: "AMD Ryzen 9",
      ram: "16GB",
      graphics: "NVIDIA GeForce RTX 3060",
    },
    reviews: [
      { user: "George", comment: "Perfect for gaming on the go!", rating: 5 },
      { user: "Helen", comment: "Compact and powerful.", rating: 4 },
    ],
  },
  {
    id: 8,
    name: "Sony Alpha a7 III Mirrorless Camera",
    price: 1999,
    rating: 4.8,
    imageUrl: "https://example.com/sonya7iii.jpg",
    description: "24.2MP full-frame mirrorless camera with exceptional image quality and autofocus.",
    category: "Cameras",
    brand: "Sony",
    specifications: {
      megapixels: "24.2MP",
      color: "Black",
      lensMount: "Sony E",
      batteryLife: "610 shots",
    },
    reviews: [
      { user: "Ivan", comment: "Amazing photo quality!", rating: 5 },
      { user: "Jenny", comment: "Great for portraits and landscapes.", rating: 4 },
    ],
  },
  {
    id: 9,
    name: "Bose QuietComfort 45 Wireless Headphones",
    price: 329,
    rating: 4.7,
    imageUrl: "https://example.com/boseqc45.jpg",
    description: "Noise-cancelling headphones with exceptional sound quality and comfort.",
    category: "Electronics",
    brand: "Bose",
    specifications: {
      color: "Triple Black",
      batteryLife: "24 hours",
      noiseCancelling: "Yes",
      microphone: "Built-in",
    },
    reviews: [
      { user: "Karen", comment: "So comfortable and clear sound.", rating: 5 },
      { user: "Leo", comment: "Best for travel.", rating: 4 },
    ],
  },
  {
    id: 10,
    name: "Fitbit Versa 3 Health & Fitness Smartwatch",
    price: 229,
    rating: 4.4,
    imageUrl: "https://example.com/fitbitversa3.jpg",
    description: "Advanced fitness tracker with built-in GPS, heart rate monitoring, and Alexa support.",
    category: "Wearables",
    brand: "Fitbit",
    specifications: {
      color: "Black/Black Aluminum",
      batteryLife: "6+ days",
      waterResistance: "50 meters",
      GPS: "Yes",
    },
    reviews: [
      { user: "Mona", comment: "Perfect for tracking workouts.", rating: 5 },
      { user: "Nick", comment: "Accurate and stylish.", rating: 4 },
    ],
  },
  // ... Continue adding products with similar details up to product 30
 
  {
    id: 11,
    name: "Logitech MX Master 3 Advanced Wireless Mouse",
    price: 99,
    rating: 4.8,
    imageUrl: "https://example.com/mxmaster3.jpg",
    description: "Advanced ergonomic mouse with ultra-fast scrolling, ideal for creative and business work.",
    category: "Accessories",
    brand: "Logitech",
    specifications: {
      color: "Graphite",
      batteryLife: "70 days",
      connectivity: "Wireless",
      dpi: "4000",
    },
    reviews: [
      { user: "Alice", comment: "Great for long working hours.", rating: 5 },
      { user: "Bob", comment: "Super smooth scrolling.", rating: 4 },
    ],
  },
  {
    id: 12,
    name: "Apple iPhone 13 Pro Max",
    price: 1099,
    rating: 4.9,
    imageUrl: "https://example.com/iphone13promax.jpg",
    description: "Apple’s latest iPhone with a Super Retina XDR display and 5G capabilities.",
    category: "Mobile Phones",
    brand: "Apple",
    specifications: {
      storage: "256GB",
      color: "Graphite",
      camera: "12MP Ultra Wide",
      batteryLife: "Up to 28 hours",
    },
    reviews: [
      { user: "Carlos", comment: "Amazing camera quality.", rating: 5 },
      { user: "Diana", comment: "Fast and sleek.", rating: 5 },
    ],
  },
  {
    id: 13,
    name: "Dyson V11 Torque Drive Cordless Vacuum",
    price: 599,
    rating: 4.7,
    imageUrl: "https://example.com/dysonv11.jpg",
    description: "High-performance cordless vacuum cleaner with intelligent suction power adjustment.",
    category: "Home Appliances",
    brand: "Dyson",
    specifications: {
      color: "Blue",
      batteryLife: "60 minutes",
      weight: "6.68 lbs",
      filter: "Whole-machine",
    },
    reviews: [
      { user: "Edward", comment: "Makes cleaning super easy.", rating: 5 },
      { user: "Fiona", comment: "Powerful and efficient.", rating: 4 },
    ],
  },
  {
    id: 14,
    name: "Nike Air Zoom Pegasus 39 Running Shoes",
    price: 120,
    rating: 4.5,
    imageUrl: "https://example.com/pegasus39.jpg",
    description: "Lightweight and comfortable running shoes with responsive cushioning.",
    category: "Footwear",
    brand: "Nike",
    specifications: {
      color: "Black/White",
      material: "Mesh upper",
      sole: "Rubber",
      weight: "8.1 oz",
    },
    reviews: [
      { user: "Greg", comment: "Feels great for long runs.", rating: 5 },
      { user: "Hanna", comment: "Very comfortable.", rating: 4 },
    ],
  },
  {
    id: 15,
    name: "Samsung Galaxy Watch 4",
    price: 249,
    rating: 4.6,
    imageUrl: "https://example.com/galaxywatch4.jpg",
    description: "Stylish smartwatch with advanced health monitoring features and Wear OS by Google.",
    category: "Wearables",
    brand: "Samsung",
    specifications: {
      color: "Black",
      batteryLife: "40 hours",
      screen: "1.4 inches",
      storage: "16GB",
    },
    reviews: [
      { user: "Isaac", comment: "Best Android watch so far!", rating: 5 },
      { user: "Julia", comment: "Great features and design.", rating: 4 },
    ],
  },
  {
    id: 16,
    name: "Dell XPS 15 Laptop",
    price: 1799,
    rating: 4.8,
    imageUrl: "https://example.com/dellxps15.jpg",
    description: "High-performance laptop with stunning 4K display and 11th Gen Intel Core i7.",
    category: "Computers",
    brand: "Dell",
    specifications: {
      storage: "512GB SSD",
      color: "Silver",
      screen: "15.6 inches 4K UHD",
      ram: "16GB",
    },
    reviews: [
      { user: "Kevin", comment: "Fantastic display and performance.", rating: 5 },
      { user: "Laura", comment: "Ideal for creative work.", rating: 4 },
    ],
  },
  {
    id: 17,
    name: "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
    price: 89,
    rating: 4.7,
    imageUrl: "https://example.com/instantpot.jpg",
    description: "Multi-use cooker with 7 cooking modes, including pressure cooking, slow cooking, and steaming.",
    category: "Kitchen Appliances",
    brand: "Instant Pot",
    specifications: {
      color: "Stainless Steel",
      capacity: "6 quarts",
      functions: "7-in-1",
      power: "1000 watts",
    },
    reviews: [
      { user: "Matt", comment: "Makes cooking so easy!", rating: 5 },
      { user: "Nina", comment: "Perfect for family meals.", rating: 4 },
    ],
  },
  {
    id: 18,
    name: "Canon EOS R5 Full-Frame Mirrorless Camera",
    price: 3899,
    rating: 4.9,
    imageUrl: "https://example.com/canoneosr5.jpg",
    description: "Professional-grade camera with 45MP sensor and 8K video recording capabilities.",
    category: "Cameras",
    brand: "Canon",
    specifications: {
      megapixels: "45MP",
      color: "Black",
      lensMount: "Canon RF",
      video: "8K",
    },
    reviews: [
      { user: "Olivia", comment: "Unmatched image quality.", rating: 5 },
      { user: "Peter", comment: "Perfect for professionals.", rating: 5 },
    ],
  },
  {
    id: 19,
    name: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
    price: 348,
    rating: 4.8,
    imageUrl: "https://example.com/wh1000xm4.jpg",
    description: "Industry-leading noise-canceling headphones with 30 hours of battery life.",
    category: "Electronics",
    brand: "Sony",
    specifications: {
      color: "Black",
      batteryLife: "30 hours",
      noiseCancelling: "Yes",
      microphone: "Yes",
    },
    reviews: [
      { user: "Quincy", comment: "Fantastic sound quality.", rating: 5 },
      { user: "Rita", comment: "Perfect for travel and work.", rating: 5 },
    ],
  },
  {
    id: 20,
    name: "Anker Soundcore Bluetooth Speaker",
    price: 59,
    rating: 4.5,
    imageUrl: "https://example.com/soundcore.jpg",
    description: "Portable Bluetooth speaker with 24-hour battery life and waterproof design.",
    category: "Audio",
    brand: "Anker",
    specifications: {
      color: "Black",
      batteryLife: "24 hours",
      waterproof: "Yes",
      connectivity: "Bluetooth",
    },
    reviews: [
      { user: "Sam", comment: "Clear sound, great battery life.", rating: 5 },
      { user: "Tina", comment: "Perfect for outdoor use.", rating: 4 },
    ],
  },
  {
    id: 21,
    name: "Samsung Galaxy Tab S7",
    price: 649,
    rating: 4.6,
    imageUrl: "https://example.com/galaxytabs7.jpg",
    description: "High-performance tablet with 11-inch display and S Pen for creative and productivity tasks.",
    category: "Tablets",
    brand: "Samsung",
    specifications: {
      color: "Mystic Black",
      batteryLife: "15 hours",
      screen: "11 inches",
      storage: "128GB",
    },
    reviews: [
      { user: "Uma", comment: "Amazing for both work and play.", rating: 5 },
      { user: "Vince", comment: "Excellent display and speed.", rating: 4 },
    ],
  },
  {
    id: 22,
    name: "MacBook Air M1",
    price: 999,
    rating: 4.9,
    imageUrl: "https://example.com/macbookairm1.jpg",
    description: "Lightweight laptop with Apple's powerful M1 chip and up to 18 hours of battery life.",
    category: "Computers",
    brand: "Apple",
    specifications: {
      storage: "256GB",
      color: "Space Gray",
      screen: "13.3 inches Retina",
      ram: "8GB",
    },
    reviews: [
      { user: "Will", comment: "Ultra-fast and efficient.", rating: 5 },
      { user: "Xena", comment: "Best for students and professionals.", rating: 5 },
    ],
  },
  {
    id: 23,
    name: "Sony A7 III Mirrorless Camera",
    price: 1999,
    rating: 4.8,
    imageUrl: "https://example.com/sonya7iii.jpg",
    description: "Full-frame mirrorless camera with 24MP sensor and excellent low-light performance.",
    category: "Cameras",
    brand: "Sony",
    specifications: {
      megapixels: "24MP",
      color: "Black",
      lensMount: "Sony E-mount",
      video: "4K",
    },
    reviews: [
      { user: "Yara", comment: "Perfect for photography enthusiasts.", rating: 5 },
      { user: "Zane", comment: "Superb quality in every shot.", rating: 5 },
    ],
  },
  {
    id: 24,
    name: "GoPro HERO9 Black",
    price: 399,
    rating: 4.7,
    imageUrl: "https://example.com/goprohero9.jpg",
    description: "High-performance action camera with 5K video and front-facing screen.",
    category: "Cameras",
    brand: "GoPro",
    specifications: {
      color: "Black",
      batteryLife: "2 hours",
      waterproof: "33ft",
      video: "5K",
    },
    reviews: [
      { user: "Aaron", comment: "Ideal for adventure videos.", rating: 5 },
      { user: "Bella", comment: "Great image stabilization.", rating: 4 },
    ],
  },
  {
    id: 25,
    name: "Fitbit Versa 3 Health & Fitness Smartwatch",
    price: 229,
    rating: 4.5,
    imageUrl: "https://example.com/fitbitversa3.jpg",
    description: "Smartwatch with heart rate monitoring, GPS, and voice assistant support.",
    category: "Wearables",
    brand: "Fitbit",
    specifications: {
      color: "Midnight Blue",
      batteryLife: "6 days",
      gps: "Yes",
      heartRateMonitor: "Yes",
    },
    reviews: [
      { user: "Chris", comment: "Awesome for fitness tracking.", rating: 5 },
      { user: "Dana", comment: "Useful health insights.", rating: 4 },
    ],
  },
];


